### ISSUE TITLE
SPath release for SCR 3.0rc1

### ISSUE THREAD

**Issue by gonsie** [ECP-VeloC/spath#10]
For SCR v3.0: https://github.com/LLNL/scr/projects/2

## Process

- [x] Merge any existing PRs
- [x] Create a commit(s) which updates the project version number in the code and updates references to any dependency versions.  
- [x] Merge the commit
- [x] Tag a release on GitHub
- [x] Add release note (can be done after the release is tagged)
- [x] Update the spack package, both with the version hash and the dependency versions.

**Comment by CamStan** [comment]
Spack package PR: https://github.com/spack/spack/pull/22625

**Comment by CamStan** [comment]
@gonsie, do we need to add anything to the spack packages for the recent rpath settings?
https://github.com/ECP-VeloC/spath/blob/2941057c53a942b0d44013ce7bd1346aa24b3539/CMakeLists.txt#L10-L13

**Comment by gonsie** [comment]
I don’t think so. I believe that spack has enough cmake smarts to DoTheRightThing™️  I think s spath just needs the versions added.
